@startuml casos_uso
left to rigth direction
actor Cliente
actor Taquilla
actor administrador
rectangle "Sistema de Reservas" {
    usecase "Realizar Reserva"
    usecase "Cancelar Reserva"
    usecase "Registrar ingreso"
    usecase "Reservar Sala"
    usecase "Generar Reportes"
}

Cliente --> "Realizar Reserva"
Cliente --> "Cancelar Reserva"
Taquilla --> "Registrar Ingreso"
Cliente --> "Reservar Sala"
administrador --> "Generar Reportes"
@enduml

